// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrmiZMy330bQq11duHX4OqVAIXCVm2KDI',
    appId: '1:371763171287:web:ae90288902e45ed9e78592',
    messagingSenderId: '371763171287',
    projectId: 'fineitune-c6fea',
    authDomain: 'fineitune-c6fea.firebaseapp.com',
    storageBucket: 'fineitune-c6fea.appspot.com',
    measurementId: 'G-4GKZRX97DS',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrmiZMy330bQq11duHX4OqVAIXCVm2KDI',
    appId: '1:371763171287:web:c9187cfb06568851e78592',
    messagingSenderId: '371763171287',
    projectId: 'fineitune-c6fea',
    authDomain: 'fineitune-c6fea.firebaseapp.com',
    storageBucket: 'fineitune-c6fea.appspot.com',
    measurementId: 'G-NVB41E0Y67',
  );

}